 ## Try labels from different experts

## Load and process raw data

In [1]:
import pandas as pd
import numpy as np

base_dir = "../data/raw/Y/ROI_6"

ROI_path_JM1 = f"{base_dir}/JM/1.xlsx"
ROI_path_JM2 = f"{base_dir}/JM/2.xlsx"

ROI_path_Dan1 = f"{base_dir}/Dan/1.xlsx"
ROI_path_Dan2 = f"{base_dir}/Dan/2.xlsx"

ROI_path_Bridget1 = f"{base_dir}/Bridget/1.xlsx"
ROI_path_Bridget2 = f"{base_dir}/Bridget/2.xlsx"

roi_MR_JM1 = pd.read_excel(ROI_path_JM1, index_col=[0, 1, 2], header=None)
roi_MR_JM2 = pd.read_excel(ROI_path_JM2, index_col=[0, 1, 2], header=None)

roi_MR_Dan1 = pd.read_excel(ROI_path_Dan1, index_col=[0, 1, 2], header=None)
roi_MR_Dan2 = pd.read_excel(ROI_path_Dan2, index_col=[0, 1, 2], header=None)

roi_MR_Bridget1 = pd.read_excel(ROI_path_Bridget1, index_col=[0, 1, 2], header=None)
roi_MR_Bridget2 = pd.read_excel(ROI_path_Bridget2, index_col=[0, 1, 2], header=None)

In [2]:
index = roi_MR_Bridget1.index

In [3]:
ck_pt = 'SM'
ck_l = 'LLSCC post'

print(roi_MR_JM1.loc[(ck_pt, 'MR',  ck_l)].values.reshape(1,3))
print(roi_MR_JM2.loc[(ck_pt, 'MR', ck_l)].values.reshape(1,3))
print(roi_MR_Dan1.loc[(ck_pt, 'MR',  ck_l)].values.reshape(1,3))
print(roi_MR_Dan2.loc[(ck_pt, 'MR', ck_l)].values.reshape(1,3))
print(roi_MR_Bridget1.loc[(ck_pt, 'MR',  ck_l)].values.reshape(1,3))
print(roi_MR_Bridget2.loc[(ck_pt, 'MR', ck_l)].values.reshape(1,3))

[[535 449  37]]
[[534 449  36]]
[[534 449  36]]
[[534 449  36]]
[[535 450  36]]
[[534 449  36]]


In [8]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))

if module_path not in sys.path:
    sys.path.append(module_path)

In [4]:
import src.models.common.MyDataset as MyDataset

names = MyDataset.get_pat_names()

landmarks = ['LLSCC ant', 'LLSCC post', 'RLSCC ant', 'RLSCC post']

all_labels = []

for pt_name in names:
    for landmark in landmarks:
        l1 = roi_MR_JM1.loc[(pt_name, 'MR',  landmark)].values.reshape(1,3)
        l2 = roi_MR_JM2.loc[(pt_name, 'MR',  landmark)].values.reshape(1,3)
        l3 = roi_MR_Dan1.loc[(pt_name, 'MR',  landmark)].values.reshape(1,3)
        l4 = roi_MR_Dan2.loc[(pt_name, 'MR',  landmark)].values.reshape(1,3)
        l5 = roi_MR_Bridget1.loc[(pt_name, 'MR',  landmark)].values.reshape(1,3)
        l6 = roi_MR_Bridget2.loc[(pt_name, 'MR',  landmark)].values.reshape(1,3)
        one_landmark = np.concatenate([l1, l2, l3, l4, l5, l6], axis=0)
        if len(all_labels) == 0:
            all_labels = one_landmark
        else:
            all_labels = np.concatenate([all_labels, one_landmark], axis=0)

In [5]:
all_labels = all_labels.reshape((20, 4, 6, 3))
print(all_labels[13, 1, :, :])
print(all_labels[0:4])

[[534 442  38]
 [532 441  38]
 [532 441  38]
 [532 441  38]
 [534 441  38]
 [533 441  38]]
[[[[540 410  44]
   [539 410  44]
   [538 411  44]
   [537 410  44]
   [539 411  44]
   [539 411  44]]

  [[535 427  42]
   [534 426  42]
   [535 426  42]
   [534 427  42]
   [535 426  42]
   [533 426  42]]

  [[240 421  50]
   [240 421  50]
   [242 421  50]
   [243 421  50]
   [241 421  50]
   [241 421  50]]

  [[248 436  47]
   [248 436  47]
   [247 436  46]
   [248 436  47]
   [246 437  47]
   [248 435  46]]]


 [[[532 441  47]
   [533 441  47]
   [530 441  47]
   [530 441  47]
   [532 441  47]
   [532 441  47]]

  [[524 453  42]
   [525 454  42]
   [524 453  42]
   [524 453  42]
   [526 454  42]
   [525 453  42]]

  [[213 446  52]
   [213 446  52]
   [215 446  51]
   [215 446  51]
   [213 446  52]
   [214 446  52]]

  [[218 459  47]
   [219 458  46]
   [219 458  46]
   [220 458  46]
   [218 459  46]
   [218 458  46]]]


 [[[557 436  51]
   [556 436  51]
   [555 436  51]
   [555 437  51]
   [5

In [6]:
medium_labels = np.median(all_labels, axis=2)

In [9]:
medium_labels_tmp = np.reshape(medium_labels, (80, 3))
print(medium_labels[0:4])

[[[539.  410.5  44. ]
  [534.5 426.   42. ]
  [241.  421.   50. ]
  [248.  436.   47. ]]

 [[532.  441.   47. ]
  [524.5 453.   42. ]
  [213.5 446.   52. ]
  [218.5 458.   46. ]]

 [[555.5 436.5  51. ]
  [552.  450.   45. ]
  [227.  435.   49.5]
  [231.  449.   43. ]]

 [[554.  426.   48. ]
  [549.  440.   45. ]
  [236.  433.   41. ]
  [241.5 448.   39. ]]]


In [7]:
all_labels_reshape = all_labels.reshape((80, 18))
save_columns = ['x', 'y', 'z', 'x', 'y', 'z', 'x', 'y', 'z', 'x', 'y', 'z', 'x', 'y', 'z', 'x', 'y', 'z']
save_index = np.asarray(['LLSCC ant', 'LLSCC post', 'RLSCC ant', 'RLSCC post'])
save_index = np.repeat(save_index.reshape(1, 4), 20, axis=0).reshape(80)

In [8]:
# save the processed Y
df1 = pd.DataFrame(all_labels_reshape,
                   index=save_index,
                   columns=save_columns)

base_save_dir = "../data/processed/Y"
df1.to_excel(f"{base_save_dir}/ROI_6.xlsx")

## Check the experts' div

In [22]:
medium_labels = medium_labels.reshape((20, 4, 1, 3))
medium_labels_rep = np.repeat(medium_labels, 6, axis=2)

In [23]:
diff_all_medium = (all_labels - medium_labels_rep) * 0.15

diff_p2 = np.power(diff_all_medium, 2)

diff_dis = np.power(np.sum(diff_p2, axis=3), 1/2)

print(np.mean(diff_dis))
print(np.std(diff_dis))

0.21566366925921088
0.2438239513699458


In [13]:
# base_save_dir = "../data/processed/Y"

# np.save(f"{base_save_dir}/ROI_MR_Medium", medium_labels)

In [32]:
# Anterior and Posterior differences from the labels
ant_diff_dis = diff_dis[:, [0, 2], :]
pos_diff_dis = diff_dis[:, [1, 3], :]

ant_diff_dis_mean = np.mean(ant_diff_dis)
ant_diff_dis_dev = np.std(ant_diff_dis)
pos_diff_dis_mean = np.mean(pos_diff_dis)
pos_diff_dis_dev = np.std(pos_diff_dis)

print(f"Anterior mean: [{ant_diff_dis_mean}], dev: [{ant_diff_dis_dev}]")
print(f"Posterior mean: [{pos_diff_dis_mean}], dev: [{pos_diff_dis_dev}]")

Anterior mean: [0.2190666918419096], dev: [0.13593577353089142]
Posterior mean: [0.21226064667651212], dev: [0.31685729101989885]


## try to upgrade from MR_medium_3 to MR_medium_6 ...

In [28]:
import numpy as np

MR_medium_6 = np.load("../data/processed/Y/ROI_MR_Medium.npy")
MR_medium_3 = np.load("../data/raw/Y/ROI_3/ROI_MR_Medium.npy")

diff = MR_medium_3 - MR_medium_6

In [30]:
#diff[:, 2:4, 0] = - diff[:, 2:4, 0]
print(diff[0:5])

[[[ 1.  -0.5  0.5]
  [ 0.5 -0.5 -0.5]
  [ 0.   0.5  0. ]
  [ 0.   0.  -0.5]]

 [[ 1.5  0.   0.5]
  [ 1.  -0.5  1. ]
  [ 0.   1.  -1. ]
  [-1.   1.   1. ]]

 [[ 0.5  1.   0. ]
  [ 2.   1.   1. ]
  [-0.5  1.  -1. ]
  [-0.5  0.5  0. ]]

 [[-2.5  0.  -0.5]
  [ 1.   1.  -1. ]
  [-1.5  0.  -0.5]
  [-1.   1.  -0.5]]

 [[ 0.  -0.5 -1. ]
  [ 1.   1.   0. ]
  [-1.   1.  -1. ]
  [ 2.  -1.5  0. ]]]


In [10]:
diff_flip = np.copy(diff)
diff_flip[:, 2:4, 0] = -diff_flip[:, 2:4, 0]
print(diff_flip[0:5])

In [11]:
np.save("../Resources/diff_flip", diff_flip)

In [80]:
import numpy as np
import importlib
import FunMRions.MyDataset as MyDataset
import FunMRions.Visualization as Visualization

pat_aug_path = "/Volumes/Shawn_HDD/PhD/ProjeMR/Date/augmentation_from_matlab/original_augmentation_data/JM_aug_1.mat"

pixel_space = [0.15, 0.15, 0.15]

importlib.reload(Visualization)

pat_aug_volume, pat_aug_pts, _ = MyDataset.load_mat_data(pat_aug_path)

print(pat_aug_pts)

Visualization.show_pts(pat_aug_volume, pat_aug_pts, pixel_space)

print(pat_aug_pts)

In [83]:
Visualization.show_pts(pat_aug_volume, medium_labels[13, :, :], pixel_space)