 ## Try labels from different experts

## Load and process raw data

In [12]:
import pandas as pd
import numpy as np

base_dir = "../data/raw/Y/ROI_6"

ROI_path_JM1 = f"{base_dir}/JM/1.xlsx"
ROI_path_JM2 = f"{base_dir}/JM/2.xlsx"

ROI_path_Dan1 = f"{base_dir}/Dan/1.xlsx"
ROI_path_Dan2 = f"{base_dir}/Dan/2.xlsx"

ROI_path_Bridget1 = f"{base_dir}/Bridget/1.xlsx"
ROI_path_Bridget2 = f"{base_dir}/Bridget/2.xlsx"

roi_CT_JM1 = pd.read_excel(ROI_path_JM1, index_col=[0, 1, 2], header=None)
roi_CT_JM2 = pd.read_excel(ROI_path_JM2, index_col=[0, 1, 2], header=None)

roi_CT_Dan1 = pd.read_excel(ROI_path_Dan1, index_col=[0, 1, 2], header=None)
roi_CT_Dan2 = pd.read_excel(ROI_path_Dan2, index_col=[0, 1, 2], header=None)

roi_CT_Bridget1 = pd.read_excel(ROI_path_Bridget1, index_col=[0, 1, 2], header=None)
roi_CT_Bridget2 = pd.read_excel(ROI_path_Bridget2, index_col=[0, 1, 2], header=None)

In [13]:
index = roi_CT_Bridget1.index

In [14]:
ck_pt = 'SM'
ck_l = 'LLSCC post'

print(roi_CT_JM1.loc[(ck_pt, 'CT',  ck_l)].values.reshape(1,3))
print(roi_CT_JM2.loc[(ck_pt, 'CT', ck_l)].values.reshape(1,3))
print(roi_CT_Dan1.loc[(ck_pt, 'CT',  ck_l)].values.reshape(1,3))
print(roi_CT_Dan2.loc[(ck_pt, 'CT', ck_l)].values.reshape(1,3))
print(roi_CT_Bridget1.loc[(ck_pt, 'CT',  ck_l)].values.reshape(1,3))
print(roi_CT_Bridget2.loc[(ck_pt, 'CT', ck_l)].values.reshape(1,3))

[[753 582 199]]
[[753 582 199]]
[[753 582 199]]
[[753 582 199]]
[[754 584 199]]
[[755 583 198]]


In [15]:
import src.models.common.MyDataset as MyDataset

names = MyDataset.get_pat_names()

landmarks = ['LLSCC ant', 'LLSCC post', 'RLSCC ant', 'RLSCC post']

all_labels = []

for pt_name in names:
    for landmark in landmarks:
        l1 = roi_CT_JM1.loc[(pt_name, 'CT',  landmark)].values.reshape(1,3)
        l2 = roi_CT_JM2.loc[(pt_name, 'CT',  landmark)].values.reshape(1,3)
        l3 = roi_CT_Dan1.loc[(pt_name, 'CT',  landmark)].values.reshape(1,3)
        l4 = roi_CT_Dan2.loc[(pt_name, 'CT',  landmark)].values.reshape(1,3)
        l5 = roi_CT_Bridget1.loc[(pt_name, 'CT',  landmark)].values.reshape(1,3)
        l6 = roi_CT_Bridget2.loc[(pt_name, 'CT',  landmark)].values.reshape(1,3)
        one_landmark = np.concatenate([l1, l2, l3, l4, l5, l6], axis=0)
        if len(all_labels) == 0:
            all_labels = one_landmark
        else:
            all_labels = np.concatenate([all_labels, one_landmark], axis=0)

In [16]:
all_labels = all_labels.reshape((20, 4, 6, 3))
print(all_labels[13, 1, :, :])
print(all_labels[0:4])

[[773 516 243]
 [772 515 242]
 [773 516 243]
 [772 516 242]
 [774 516 241]
 [773 515 241]]
[[[[757 448 207]
   [757 450 206]
   [757 449 206]
   [756 450 207]
   [758 449 207]
   [758 450 206]]

  [[751 479 207]
   [750 478 206]
   [751 479 205]
   [750 479 206]
   [751 478 205]
   [749 477 205]]

  [[243 473 214]
   [243 475 214]
   [244 474 213]
   [245 475 214]
   [243 475 214]
   [242 474 213]]

  [[256 501 209]
   [256 502 209]
   [254 502 208]
   [256 501 208]
   [256 502 208]
   [255 502 209]]]


 [[[795 524 246]
   [797 524 247]
   [795 524 246]
   [795 525 246]
   [797 524 247]
   [796 525 247]]

  [[780 542 231]
   [780 543 231]
   [781 542 231]
   [781 544 231]
   [782 542 232]
   [781 544 232]]

  [[245 485 224]
   [246 485 224]
   [248 485 224]
   [248 485 224]
   [246 486 223]
   [244 488 223]]

  [[256 508 209]
   [256 507 209]
   [255 507 208]
   [256 507 209]
   [255 508 210]
   [256 507 208]]]


 [[[809 587 278]
   [808 587 278]
   [807 587 278]
   [807 586 277]
   [8

In [17]:
medium_labels = np.median(all_labels, axis=2)

In [18]:
medium_labels_tmp = np.reshape(medium_labels, (80, 3))
print(medium_labels[0:4])

[[[757.  449.5 206.5]
  [750.5 478.5 205.5]
  [243.  474.5 214. ]
  [256.  502.  208.5]]

 [[795.5 524.  246.5]
  [781.  542.5 231. ]
  [246.  485.  224. ]
  [256.  507.  209. ]]

 [[808.5 587.  278. ]
  [798.  609.  261. ]
  [240.5 522.  283. ]
  [246.5 547.5 264. ]]

 [[797.5 438.  240.5]
  [785.  458.  226. ]
  [249.5 364.  269.5]
  [256.  387.  254.5]]]


In [19]:
all_labels_reshape = all_labels.reshape((80, 18))
save_columns = ['x', 'y', 'z', 'x', 'y', 'z', 'x', 'y', 'z', 'x', 'y', 'z', 'x', 'y', 'z', 'x', 'y', 'z']
save_index = np.asarray(['LLSCC ant', 'LLSCC post', 'RLSCC ant', 'RLSCC post'])
save_index = np.repeat(save_index.reshape(1, 4), 20, axis=0).reshape(80)

In [20]:
# # save the processed Y
# df1 = pd.DataFrame(all_labels_reshape,
#                    index=save_index,
#                    columns=save_columns)
# df1.to_excel("../Resources/ROI/ROI_6.xlsx")

## Check the experts' div

In [22]:
medium_labels = medium_labels.reshape((20, 4, 1, 3))
medium_labels_rep = np.repeat(medium_labels, 6, axis=2)

In [23]:
diff_all_medium = (all_labels - medium_labels_rep) * 0.15

diff_p2 = np.power(diff_all_medium, 2)

diff_dis = np.power(np.sum(diff_p2, axis=3), 1/2)

print(np.mean(diff_dis))
print(np.std(diff_dis))

0.21566366925921088
0.2438239513699458


In [26]:
# base_save_dir = "../data/processed/Y"
# 
# np.save(f"{base_save_dir}/ROI_CT_Medium", medium_labels)

In [32]:
# Anterior and Posterior differences from the labels
ant_diff_dis = diff_dis[:, [0, 2], :]
pos_diff_dis = diff_dis[:, [1, 3], :]

ant_diff_dis_mean = np.mean(ant_diff_dis)
ant_diff_dis_dev = np.std(ant_diff_dis)
pos_diff_dis_mean = np.mean(pos_diff_dis)
pos_diff_dis_dev = np.std(pos_diff_dis)

print(f"Anterior mean: [{ant_diff_dis_mean}], dev: [{ant_diff_dis_dev}]")
print(f"Posterior mean: [{pos_diff_dis_mean}], dev: [{pos_diff_dis_dev}]")

Anterior mean: [0.2190666918419096], dev: [0.13593577353089142]
Posterior mean: [0.21226064667651212], dev: [0.31685729101989885]


## try to upgrade from ct_medium_3 to ct_medium_6 ...

In [28]:
import numpy as np

ct_medium_6 = np.load("../data/processed/Y/ROI_CT_Medium.npy")
ct_medium_3 = np.load("../data/raw/Y/ROI_3/ROI_CT_Medium.npy")

diff = ct_medium_3 - ct_medium_6

In [30]:
#diff[:, 2:4, 0] = - diff[:, 2:4, 0]
print(diff[0:5])

[[[ 1.  -0.5  0.5]
  [ 0.5 -0.5 -0.5]
  [ 0.   0.5  0. ]
  [ 0.   0.  -0.5]]

 [[ 1.5  0.   0.5]
  [ 1.  -0.5  1. ]
  [ 0.   1.  -1. ]
  [-1.   1.   1. ]]

 [[ 0.5  1.   0. ]
  [ 2.   1.   1. ]
  [-0.5  1.  -1. ]
  [-0.5  0.5  0. ]]

 [[-2.5  0.  -0.5]
  [ 1.   1.  -1. ]
  [-1.5  0.  -0.5]
  [-1.   1.  -0.5]]

 [[ 0.  -0.5 -1. ]
  [ 1.   1.   0. ]
  [-1.   1.  -1. ]
  [ 2.  -1.5  0. ]]]


In [10]:
diff_flip = np.copy(diff)
diff_flip[:, 2:4, 0] = -diff_flip[:, 2:4, 0]
print(diff_flip[0:5])

In [11]:
np.save("../Resources/diff_flip", diff_flip)

In [80]:
import numpy as np
import importlib
import Functions.MyDataset as MyDataset
import Functions.Visualization as Visualization

pat_aug_path = "/Volumes/Shawn_HDD/PhD/Project/Date/augmentation_from_matlab/original_augmentation_data/JM_aug_1.mat"

pixel_space = [0.15, 0.15, 0.15]

importlib.reload(Visualization)

pat_aug_volume, pat_aug_pts, _ = MyDataset.load_mat_data(pat_aug_path)

print(pat_aug_pts)

Visualization.show_pts(pat_aug_volume, pat_aug_pts, pixel_space)

print(pat_aug_pts)

In [83]:
Visualization.show_pts(pat_aug_volume, medium_labels[13, :, :], pixel_space)