In [28]:
import tensorflow as tf

model = tf.keras.Sequential()
#model.add(tf.keras.layers.Dense(16))
model.add(tf.keras.layers.BatchNormalization())

input_shape = (2,3,2)
model_build = model.build(input_shape)

In [29]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 batch_normalization_1 (Batc  (2, 3, 2)                8         
 hNormalization)                                                 
                                                                 
Total params: 8
Trainable params: 4
Non-trainable params: 4
_________________________________________________________________


In [30]:
model.weights

[<tf.Variable 'batch_normalization_1/gamma:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>,
 <tf.Variable 'batch_normalization_1/beta:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'batch_normalization_1/moving_mean:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'batch_normalization_1/moving_variance:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>]

In [31]:
import numpy as np

a2 = np.arange(2*3*2).reshape(2,3,2)

b2= model(a2, training=True)

In [32]:
model.weights

[<tf.Variable 'batch_normalization_1/gamma:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>,
 <tf.Variable 'batch_normalization_1/beta:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'batch_normalization_1/moving_mean:0' shape=(2,) dtype=float32, numpy=array([0.05, 0.06], dtype=float32)>,
 <tf.Variable 'batch_normalization_1/moving_variance:0' shape=(2,) dtype=float32, numpy=array([1.1066667, 1.1066667], dtype=float32)>]

In [33]:
c2 = model(a2, training=False)
print(a2)
print(b2)
print(c2)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
tf.Tensor(
[[[-1.4637873  -1.4637873 ]
  [-0.8782724  -0.87827235]
  [-0.2927575  -0.2927574 ]]

 [[ 0.2927574   0.2927574 ]
  [ 0.8782723   0.8782724 ]
  [ 1.4637873   1.4637872 ]]], shape=(2, 3, 2), dtype=float32)
tf.Tensor(
[[[-0.04750786  0.8931477 ]
  [ 1.8528064   2.793462  ]
  [ 3.753121    4.6937766 ]]

 [[ 5.653435    6.594091  ]
  [ 7.5537496   8.494405  ]
  [ 9.454063   10.394719  ]]], shape=(2, 3, 2), dtype=float32)


In [6]:
from tensorflow import keras

model_path = "/Users/achs/PhD/code/CT-MRI_LandmarkDetection/Spartan/trained_models/cropped_dataset/straight_model/one_landmark_res/bestVal_straight_model_cropped_150x150x100"

trained_model = keras.models.load_model(model_path)

In [8]:
trained_model.summary()

Model: "straight-3d-cnn"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 150, 150, 100, 1  0         
                             )]                                  
                                                                 
 conv3d (Conv3D)             (None, 150, 150, 100, 32  896       
                             )                                   
                                                                 
 batch_normalization (BatchN  (None, 150, 150, 100, 32  128      
 ormalization)               )                                   
                                                                 
 re_lu (ReLU)                (None, 150, 150, 100, 32  0         
                             )                                   
                                                                 
 max_pooling3d (MaxPooling3D  (None, 75, 75, 50, 32

In [10]:
layers = trained_model.layers
weights = trained_model.weights

In [14]:
layers[2].get_config()

{'name': 'batch_normalization',
 'trainable': True,
 'dtype': 'float32',
 'axis': ListWrapper([4]),
 'momentum': 0.99,
 'epsilon': 0.001,
 'center': True,
 'scale': True,
 'beta_initializer': {'class_name': 'Zeros', 'config': {}},
 'gamma_initializer': {'class_name': 'Ones', 'config': {}},
 'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
 'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
 'beta_regularizer': None,
 'gamma_regularizer': None,
 'beta_constraint': None,
 'gamma_constraint': None}

In [19]:
weights[2:6]

[<tf.Variable 'batch_normalization/gamma:0' shape=(32,) dtype=float32, numpy=
 array([1.0017833 , 0.99791384, 1.0022452 , 1.0005289 , 1.0004532 ,
        1.0164363 , 0.99942285, 0.99703526, 1.0014154 , 1.0006273 ,
        0.9989771 , 0.9973664 , 0.9983925 , 0.996177  , 0.99530715,
        0.995015  , 0.9985827 , 0.99801785, 0.9939523 , 0.9989443 ,
        1.0111473 , 1.0013007 , 0.99996483, 0.99831975, 1.0019885 ,
        0.9835751 , 0.9930419 , 1.0005544 , 0.9944062 , 1.0004566 ,
        1.0073248 , 1.0071582 ], dtype=float32)>,
 <tf.Variable 'batch_normalization/beta:0' shape=(32,) dtype=float32, numpy=
 array([-1.5805269e-03, -3.0286511e-04, -1.1041384e-02, -7.6116635e-03,
        -1.0530146e-02, -4.3934416e-03, -1.2578647e-02,  6.7152258e-04,
        -7.1763610e-03,  2.1894912e-03, -5.0182804e-03, -4.6163015e-03,
        -3.2768322e-03, -7.9420051e-03, -1.1459227e-02, -1.8927818e-02,
         2.9145291e-03, -9.1901198e-03, -5.7523628e-03, -1.2546073e-02,
        -7.2146364e-04, -6.

In [17]:
layers[2].get_weights()

[array([1.0017833 , 0.99791384, 1.0022452 , 1.0005289 , 1.0004532 ,
        1.0164363 , 0.99942285, 0.99703526, 1.0014154 , 1.0006273 ,
        0.9989771 , 0.9973664 , 0.9983925 , 0.996177  , 0.99530715,
        0.995015  , 0.9985827 , 0.99801785, 0.9939523 , 0.9989443 ,
        1.0111473 , 1.0013007 , 0.99996483, 0.99831975, 1.0019885 ,
        0.9835751 , 0.9930419 , 1.0005544 , 0.9944062 , 1.0004566 ,
        1.0073248 , 1.0071582 ], dtype=float32),
 array([-1.5805269e-03, -3.0286511e-04, -1.1041384e-02, -7.6116635e-03,
        -1.0530146e-02, -4.3934416e-03, -1.2578647e-02,  6.7152258e-04,
        -7.1763610e-03,  2.1894912e-03, -5.0182804e-03, -4.6163015e-03,
        -3.2768322e-03, -7.9420051e-03, -1.1459227e-02, -1.8927818e-02,
         2.9145291e-03, -9.1901198e-03, -5.7523628e-03, -1.2546073e-02,
        -7.2146364e-04, -6.6961036e-03, -5.2175396e-03, -8.9530889e-03,
        -3.8278447e-03, -2.0324115e-02, -4.8981899e-05, -7.2749157e-04,
        -2.0074942e-05, -1.1932737e-02,