In [8]:
import tensorflow as tf

model = tf.keras.Sequential()
#model.add(tf.keras.layers.Dense(16))
model.add(tf.keras.layers.BatchNormalization())

input_shape = (2,3)
model.build(input_shape)

In [9]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 batch_normalization_5 (Batc  (2, 3)                   12        
 hNormalization)                                                 
                                                                 
Total params: 12
Trainable params: 6
Non-trainable params: 6
_________________________________________________________________


In [10]:
import numpy as np

a = np.arange(2*3).reshape(2,3)

b= model(a)

In [12]:
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
tf.Tensor(
[[0.        0.9995004 1.9990008]
 [2.9985013 3.9980016 4.997502 ]], shape=(2, 3), dtype=float32)
