In [22]:
import tensorflow as tf

model = tf.keras.Sequential()
#model.add(tf.keras.layers.Dense(16))
model.add(tf.keras.layers.BatchNormalization())

input_shape = (2,3)
model_build = model.build(input_shape)

In [23]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 batch_normalization_7 (Batc  (2, 3)                   12        
 hNormalization)                                                 
                                                                 
Total params: 12
Trainable params: 6
Non-trainable params: 6
_________________________________________________________________


In [27]:
model.weights

[<tf.Variable 'batch_normalization_7/gamma:0' shape=(3,) dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>,
 <tf.Variable 'batch_normalization_7/beta:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'batch_normalization_7/moving_mean:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>,
 <tf.Variable 'batch_normalization_7/moving_variance:0' shape=(3,) dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>]

In [19]:
import numpy as np

a = np.arange(5*3).reshape(5,3)

b= model(a, training=False)

In [20]:
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
tf.Tensor(
[[ 0.         0.9995004  1.9990008]
 [ 2.9985013  3.9980016  4.997502 ]
 [ 5.9970026  6.996503   7.996003 ]
 [ 8.995503   9.995004  10.994504 ]
 [11.994005  12.9935055 13.993006 ]], shape=(5, 3), dtype=float32)
