# Process the data (combine them together)

## Check JH's augmentation data

In [ ]:
import importlib
import Functions.MyDataset as MyDataset
import Functions.Visualization as Visualization

JH_aug_mat_path = "/Volumes/Shawn_SSD/PhD/Project/Date/Tmp/JH_Pre_Augmentation/original_augmentation_data/JH_aug_2.mat"
JH_reshape_vol_mat_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_from_matlab/Val/Input/FA_17017030_AugVol_2.mat"
JH_reshape_pts_mat_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_from_matlab/Val/Output/FA_17017030_AugPts_2.mat"

pixel_space = [0.15, 0.15, 0.15]

importlib.reload(MyDataset)

# JH_aug_volume, JH_aug_pts = functions.load_mat_data(JH_aug_mat_path)
# functions.show_pts(JH_aug_volume, JH_aug_pts, pixel_space)

JH_aug_zoomed_volume, JH_aug_zoomed_pts = MyDataset.load_mat_data(JH_reshape_vol_mat_path, JH_reshape_pts_mat_path)
Visualization.show_pts(JH_aug_zoomed_volume, JH_aug_zoomed_pts, pixel_space)


In [ ]:
# Try up_sampling method

up_sampling_JH = MyDataset.rescale_3d_volume(JH_aug_zoomed_volume, (512, 512, 90))
Visualization.show_pts(up_sampling_JH, JH_aug_zoomed_pts, pixel_space)

## Check rescaled data

In [ ]:
import importlib
import Functions

# data_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_rescaled_data/176_176_48/AH_17617648_VolPts_3.mat"
# data_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_rescaled_data/240_240_64/AH_24024064_VolPts_3.mat"
# data_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_rescaled_data/320_320_96/AH_32032096_VolPts_3.mat"
# data_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_rescaled_data/480_480_128/AH_480480128_VolPts_3.mat"
data_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_rescaled_data/560_560_160/AH_560560160_VolPts_3.mat"

aug_rescaled_volume, aug_rescaled_pts = MyDataset.load_mat_data(data_path)

pixel_space = [0.15, 0.15, 0.15]
Visualization.show_pts(aug_rescaled_volume, aug_rescaled_pts, pixel_space)

## Combination

In [ ]:
import numpy as np
import importlib
import Functions

def combine_data(x_base_path, y_base_path, store_base_path, data_tag):
    importlib.reload(MyDataset)

    # X_val_base_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_from_matlab/Val/Input"
    # Y_val_base_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_from_matlab/Val/Output"

    x_dataset, y_dataset = MyDataset.load_mat_data_dir(x_base_path, y_base_path)

    x_dataset = np.asarray(x_dataset)
    y_dataset = np.asarray(y_dataset)

    x_dataset_path = store_base_path + "X_" + data_tag + "_data"
    y_dataset_path = store_base_path + "Y_" + data_tag + "_data"

    np.save(x_dataset_path, x_dataset)
    np.save(y_dataset_path, y_dataset)


In [ ]:
X_train_base_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_from_matlab/Train/Input"
Y_train_base_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_from_matlab/Train/Output"
X_val_base_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_from_matlab/Val/Input"
Y_val_base_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_from_matlab/Val/Output"
X_test_base_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_from_matlab/Test/Input"
Y_test_base_path = "/Volumes/Shawn_SSD/PhD/Project/Date/augmentation_from_matlab/Test/Output"
store_base_path = "data/"

combine_data(X_train_base_path, Y_train_base_path, store_base_path, "train")
combine_data(X_val_base_path, Y_val_base_path, store_base_path, "val")
combine_data(X_test_base_path, Y_test_base_path, store_base_path, "test")

In [ ]:
import numpy as np
import Functions

# Inspect Loaded Data

X_file_path = "data/X_train_data.npy"
Y_file_path = "data/Y_train_data.npy"

X_load = np.load(X_file_path, allow_pickle=True)
Y_load = np.load(Y_file_path, allow_pickle=True)

print(np.shape(X_load), np.shape(Y_load))
print(np.shape(X_load[1, :, :, :]), np.shape(Y_load[1, :, :]))

# functions.show_pts(X_load[1, :, :, :], Y_load[1, :, :], [0.15, 0.15, 0.15])
# functions.show_pts(X_load[2, :, :, :], Y_load[2, :, :], [0.15, 0.15, 0.15])
# functions.show_pts(X_load[3, :, :, :], Y_load[3, :, :], [0.15, 0.15, 0.15])
# functions.show_pts(X_load[4, :, :, :], Y_load[4, :, :], [0.15, 0.15, 0.15])

## Check slr model

In [62]:
import Spartan.models as models
import importlib

importlib.reload(models)

model = models.spine_lateral_radiograph_model(width=48, height=48, depth=32)
model.summary()

Model: "ResModel"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_17 (InputLayer)          [(None, 48, 48, 32,  0           []                               
                                 1)]                                                              
                                                                                                  
 batch_normalization_342 (Batch  (None, 48, 48, 32,   4          ['input_17[0][0]']               
 Normalization)                 1)                                                                
                                                                                                  
 re_lu_342 (ReLU)               (None, 48, 48, 32,   0           ['batch_normalization_342[0][0]']
                                1)                                                         

In [57]:
import numpy as np

importlib.reload(models)

# check the pre-defined coordinate matrix
batch_base_cor_xyz = models.coordinate_3d(2,2,3,4)

# test base coordinate matrix
print("batch_base_cor_xyz shape: ", np.shape(batch_base_cor_xyz))
print(batch_base_cor_xyz[0, :, :, 3, 1, 2])

batch_base_cor_xyz shape:  (2, 2, 3, 4, 4, 3)
[[0.75 0.75 0.75]
 [0.75 0.75 0.75]]


In [ ]:
from tensorflow import keras

# draw a graph for the model's
keras.utils.plot_model(model, "slr_model.png", show_shapes=True)

In [58]:
import tensorflow as tf

# check tf.repeat
pro_matricx = np.arange(2*3*4*5*4).reshape(2,3,4,5,4)
dup_pro_matricx = tf.repeat(pro_matricx, 3, axis=-1)

#print(pro_matricx)

# print(np.shape(dup_pro_matricx))
dup_pro_matricx = np.reshape(dup_pro_matricx, (2,3,4,5,4,3))
print(dup_pro_matricx[:,:,:,:,:,2])

[[[[[  0   1   2   3]
    [  4   5   6   7]
    [  8   9  10  11]
    [ 12  13  14  15]
    [ 16  17  18  19]]

   [[ 20  21  22  23]
    [ 24  25  26  27]
    [ 28  29  30  31]
    [ 32  33  34  35]
    [ 36  37  38  39]]

   [[ 40  41  42  43]
    [ 44  45  46  47]
    [ 48  49  50  51]
    [ 52  53  54  55]
    [ 56  57  58  59]]

   [[ 60  61  62  63]
    [ 64  65  66  67]
    [ 68  69  70  71]
    [ 72  73  74  75]
    [ 76  77  78  79]]]


  [[[ 80  81  82  83]
    [ 84  85  86  87]
    [ 88  89  90  91]
    [ 92  93  94  95]
    [ 96  97  98  99]]

   [[100 101 102 103]
    [104 105 106 107]
    [108 109 110 111]
    [112 113 114 115]
    [116 117 118 119]]

   [[120 121 122 123]
    [124 125 126 127]
    [128 129 130 131]
    [132 133 134 135]
    [136 137 138 139]]

   [[140 141 142 143]
    [144 145 146 147]
    [148 149 150 151]
    [152 153 154 155]
    [156 157 158 159]]]


  [[[160 161 162 163]
    [164 165 166 167]
    [168 169 170 171]
    [172 173 174 175]
    [176 177

In [63]:
import numpy as np

# check output of the model
input = np.arange(2*48*48*32*1).reshape(2,48,48,32,1)
base_cor_xyz = models.coordinate_3d(2,48,48,32)

[output_s1, output_s2] = model([input, base_cor_xyz])

print(np.shape(output_s1))
print(np.shape(output_s2))


(2, 4, 3)
(2, 4, 3)


In [26]:
importlib.reload(models)

# check loss function
y_true = np.asarray([[[1,2,3],[2,3,4],[6,7,8],[7,8,9]], [[1.5,2.5,3.5],[2.5,3.5,4.5],[6.5,7.5,8.5],[7.5,8.5,9.5]]])

y_pred1 = np.asarray([[[1,2,3],[2,3,4],[6,7,8],[7,8,9]], [[1.5,2.5,3.5],[2.5,3.5,4.5],[6.5,7.5,8.5],[7.5,8.5,9.5]]])
y_pred2 = np.asarray([[[1,2,3],[2,3,4],[6,7,8],[7,8,9]], [[1.5,2.5,3.5],[2.5,3.5,4.5],[6.5,7.5,8.5],[7.5,8.5,9.5]]])

loss = models.two_stage_wing_loss(y_true, [output_s1, output_s2])

print(loss)

tf.Tensor(347.10425, shape=(), dtype=float32)


## Straight 3d CNN

In [3]:
import Spartan.models as models
import importlib

importlib.reload(models)

s_model = models.straight_model()
s_model.summary()

Model: "straight-3d-cnn"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 176, 176, 48, 1)  0         
                             ]                                   
                                                                 
 conv3d_24 (Conv3D)          (None, 176, 176, 48, 32)  896       
                                                                 
 batch_normalization_24 (Bat  (None, 176, 176, 48, 32)  128      
 chNormalization)                                                
                                                                 
 re_lu_24 (ReLU)             (None, 176, 176, 48, 32)  0         
                                                                 
 max_pooling3d_8 (MaxPooling  (None, 88, 88, 24, 32)   0         
 3D)                                                             
                                                   