## Translation Noises

In [1]:
# The noises from --> Training Dataset's predictions in Step1's Model

import Functions.MyDataset as MyDataset

MyDataset.get_pat_from_idx(301, True)

('DM', 1)

In [2]:
import numpy as np

Y_pred_dir = "/Users/achs/PhD/code/CT-MRI_LandmarkDetection/Spartan/trained_models/divided_dataset/straight_model/mean_two_landmarks/"

Y_eva_pred_file = "bestVal_straight_model_divided_176_88_48_mean_two_landmarks_all_p.npy"
Y_eva_gt_file = "straight_model_divided_176_88_48_mean_two_landmarks_all_gt.npy"
Y_eva_err_dis_file = "bestVal_straight_model_divided_176_88_48_mean_two_landmarks_all_err_dis.npy"

Y_eva_pred_path = Y_pred_dir + Y_eva_pred_file
Y_eva_pred = np.load(Y_eva_pred_path)

Y_eva_gt_path = Y_pred_dir + Y_eva_gt_file
Y_eva_gt_read = np.load(Y_eva_gt_path)

Y_eva_err_dis_path = Y_pred_dir + Y_eva_err_dis_file
Y_eva_err_dis = np.load(Y_eva_err_dis_path)

In [3]:
data_splits = MyDataset.get_data_splits(True, True)

Y_eva_err_dis_train = Y_eva_err_dis[data_splits[0]]
Y_eva_err_dis_val = Y_eva_err_dis[data_splits[1]]
Y_eva_err_dis_test = Y_eva_err_dis[data_splits[2]]

In [4]:
print(Y_eva_err_dis_val)

[[[-1.67248517e-01 -1.52246088e-01 -6.84525907e-01]]

 [[ 2.29901209e-01 -9.64470196e+00  3.71760035e+00]]

 [[-3.37919617e+00  2.90193439e+00  4.46545124e-01]]

 [[ 2.24358726e+00 -7.47663915e-01 -2.87058890e-01]]

 [[-9.77978230e-01 -2.59512514e-01  4.72910434e-01]]

 [[ 1.32068861e+00  3.61212790e-01 -1.48934889e+00]]

 [[-8.18213403e-01  1.02380383e+00 -2.86571264e-01]]

 [[ 2.19893050e+00  5.45873158e-02 -5.16794682e-01]]

 [[ 8.12610984e-02  3.69658262e-01 -7.67876878e-02]]

 [[ 2.04696441e+00  2.22663924e-01 -4.30187315e-01]]

 [[-5.67276812e+00  5.17895555e+00  8.54566693e-01]]

 [[ 2.04791331e+00 -6.79705501e-01 -9.82636213e-01]]

 [[-3.07388157e-01  1.55467987e-01  3.79875183e-01]]

 [[ 1.78036547e+00  2.59559155e-01 -1.76684618e-01]]

 [[-9.93011534e-01  1.20408499e+00  7.52390325e-01]]

 [[ 2.57263422e+00 -4.18860286e-01 -8.48219451e-03]]

 [[-4.01968384e+00  3.27421021e+00  7.27761090e-01]]

 [[ 2.29196692e+00 -6.38134181e-01 -5.02302468e-01]]

 [[-2.63166040e-01  7.789974

In [8]:
square_err_diff = np.power(Y_eva_err_dis_val, 2)
sum_square_err_diff = np.sum(square_err_diff, axis= (1,2) )

min_err_idx = np.argmin(sum_square_err_diff, axis=0)
max_err_idx = np.argmax(sum_square_err_diff, axis=0)
print(f"Min[{min_err_idx}]: {sum_square_err_diff[min_err_idx]}")
print(f"Max[{max_err_idx}]: {sum_square_err_diff[max_err_idx]}")
print(f"Mean: {np.mean(sum_square_err_diff)}")

Min[94]: 0.10620573908090591
Max[1]: 106.89368438720703
Mean: 6.087070465087891


In [9]:
print(sum_square_err_diff[1:100])

[1.06893684e+02 2.00395927e+01 5.67508793e+00 1.24743235e+00
 4.09285307e+00 1.79977047e+00 5.10535145e+00 1.49146929e-01
 4.42470360e+00 5.97321625e+01 5.62152195e+00 2.62962937e-01
 3.26828933e+00 3.00198364e+00 6.79396296e+00 2.74079475e+01
 5.91263533e+00 7.05951631e-01 8.00029659e+00 7.66792953e-01
 7.94391680e+00 3.87222719e+00 3.55171585e+00 1.23419666e+01
 4.76510376e-01 1.00418558e+01 5.75142002e+00 5.46240926e-01
 6.70896626e+00 3.46466005e-01 5.18828201e+00 3.33222002e-01
 3.36918020e+00 5.77111602e-01 1.18498077e+01 1.16911329e-01
 4.80179977e+00 6.61140976e+01 6.23606396e+00 8.63546753e+01
 6.66676378e+00 4.66888249e-01 4.45785856e+00 1.58039123e-01
 7.13528967e+00 2.14415908e-01 6.21598339e+00 3.23765802e+00
 3.17340565e+00 1.39006197e+00 4.15516233e+00 7.94045746e-01
 6.26343060e+00 9.66257629e+01 6.27937651e+00 2.13311100e+01
 5.54746580e+00 8.22325516e+00 4.56937408e+00 3.24018300e-01
 4.16272306e+00 2.69994110e-01 8.47212982e+00 1.03909035e+01
 5.08674574e+00 2.487409